### PR TITLE
Validation Rules API support

### PR DESCRIPTION
**Pull request by jordansexton**
This PR enables accessing the validation rules API through the SDK at

```javascript
client.validationRules.create(validationRule, callback)
client.validationRules.get(validationRuleId, callback)
client.validationRules.update(validationRuleId, validationRule, callback)
client.validationRules.delete(validationRuleId, callback)
```

It includes passing tests and follows the code style of the project.

### CODE REVIEW

**Comment by frakti** [comment]
@jordansexton Thanks for your contribution, we're reviewing your PRs!
We should release your changes soon.

**Comment by jordansexton** [comment]
@frakti Sounds good, thanks!

**Comment by frakti** [comment]
@jordansexton your code is not compliant with standardjs, could you run `standard --fix`?

**Comment by jordansexton** [comment]
Just fixed, I can rebase if desired.

**Comment by frakti** [comment]
Thanks!

**Pull request merged**
